#pragma once

#define OBD_QUERY_CANID 0x7DF

#define OBD_RESPONSE_CANID_MIN 0x7E8
#define OBD_RESPONSE_CANID_MAX 0x7EF

enum obd_service_modes
{
    OBD_SERVICE_SHOW_CURRENT_DATA = 0x01,
    OBD_SERVICE_SHOW_FREEZE_FRAME_DATA = 0x02,
    OBD_SERVICE_SHOW_STORED_TROUBLE_CODES = 0x03,
    OBD_SERVICE_CLEAR_TROUBLE_CODES = 0x04,
    OBD_SERVICE_TEST_RESULTS = 0x06,
    OBD_SERVICE_SHOW_PENDING_TROUBLE_CODES = 0x07,
    OBD_SERVICE_CONTROL_OPERATION = 0x08,
    OBD_SERVICE_REQUEST_VEHICLE_INFORMATION = 0x09,
    OBD_SERVICE_PERMANENT_TROUBLE_CODES = 0x0A
};

enum OBD_PIDS_SERVICE_1 // Service 1: Show Current Data
{
    OBD_PIDS_SUPPORTED_1_TO_20         = 0x00,
    OBD_PIDS_MONITOR_STATUS                 = 0x01,
    OBD_PIDS_FREEZE_FRAME_DTC               = 0x02,
    OBD_PIDS_FUEL_SYSTEM_STATUS             = 0x03,
    OBD_PIDS_CALCULATED_ENGINE_LOAD         = 0x04,
    OBD_PIDS_ENGINE_COOLANT_TEMPERATURE     = 0x05,
    OBD_PIDS_STFT_BANK_1                    = 0x06,
    OBD_PIDS_LTFT_BANK_1                    = 0x07,
    OBD_PIDS_STFT_BANK_2                    = 0x08,
    OBD_PIDS_LTFT_BANK_2                    = 0x09,
    OBD_PIDS_FUEL_PRESSURE                  = 0x0A,
    OBD_PIDS_INTAKE_MANIFOLD_PRESSURE_ABS   = 0x0B,
    OBD_PIDS_ENGINE_SPEED                   = 0x0C,
    OBD_PIDS_VEHICLE_SPEED                  = 0x0D,
    OBD_PIDS_TIMING_ADVANCE                 = 0x0E,
    OBD_PIDS_INTAKE_AIR_TEMPERATURE         = 0x0F,
    OBD_PIDS_MASS_AIR_FLOW_RATE             = 0x10,
    OBD_PIDS_THROTTLE_POSITION              = 0x11,
    OBD_PIDS_COMMANDED_SECONDARY_AIR_STATUS = 0x12,
    OBD_PIDS_OXYGEN_SENSORS_PRESENT_2_BANKS = 0x13,
    OBD_PIDS_OXYGEN_SENSOR_1_VOLTAGE_STFT   = 0x14,
    OBD_PIDS_OXYGEN_SENSOR_2_VOLTAGE_STFT   = 0x15,
    OBD_PIDS_OXYGEN_SENSOR_3_VOLTAGE_STFT   = 0x16,
    OBD_PIDS_OXYGEN_SENSOR_4_VOLTAGE_STFT   = 0x17,
    OBD_PIDS_OXYGEN_SENSOR_5_VOLTAGE_STFT   = 0x18,
    OBD_PIDS_OXYGEN_SENSOR_6_VOLTAGE_STFT   = 0x19,
    OBD_PIDS_OXYGEN_SENSOR_7_VOLTAGE_STFT   = 0x1A,
    OBD_PIDS_OXYGEN_SENSOR_8_VOLTAGE_STFT   = 0x1B,
    OBD_PIDS_OBD_STANDARDS_COMFORM_TO       = 0x1C,
    OBD_PIDS_OXYGEN_SENSORS_PRESENT_4_BANKS = 0x1D,
    OBD_PIDS_AUXILIARY_INPUT_STATUS         = 0x1E,
    OBD_PIDS_RUN_TIME_SINCE_ENGINE_START    = 0x1F,
    OBD_PIDS_SUPPORTED_21_TO_40        = 0x20,
    OBD_PIDS_DISTANCE_TRAVELLED_WITH_MIL    = 0x21,  //  Distance travelled with the malfunction indicator lamp on.
    OBD_PIDS_FUEL_RAIL_PRESSURE             = 0x22,
    OBD_PIDS_FUEL_RAIL_GAUGE_PRESSURE       = 0x23,
    OBD_PIDS_OXYGEN_SENSOR_1_AIR_FUEL_RATIO_VOLTAGE = 0x24,
    OBD_PIDS_OXYGEN_SENSOR_2_AIR_FUEL_RATIO_VOLTAGE = 0x25,
    OBD_PIDS_OXYGEN_SENSOR_3_AIR_FUEL_RATIO_VOLTAGE = 0x26,
    OBD_PIDS_OXYGEN_SENSOR_4_AIR_FUEL_RATIO_VOLTAGE = 0x27,
    OBD_PIDS_OXYGEN_SENSOR_5_AIR_FUEL_RATIO_VOLTAGE = 0x28,
    OBD_PIDS_OXYGEN_SENSOR_6_AIR_FUEL_RATIO_VOLTAGE = 0x29,
    OBD_PIDS_OXYGEN_SENSOR_7_AIR_FUEL_RATIO_VOLTAGE = 0x2A,
    OBD_PIDS_OXYGEN_SENSOR_8_AIR_FUEL_RATIO_VOLTAGE = 0x2B,
    OBD_PIDS_COMMANDED_EGR                  = 0x2C,
    OBD_PIDS_EGR_ERROR                      = 0x2D,
    OBD_PIDS_COMMANDED_EVAPORATIVE_PURGE    = 0x2E,
    OBD_PIDS_FUEL_TANK_LEVEL_INPUT          = 0x2F,
    OBD_PIDS_WARM_UPS_SINCE_CODES_CLEARED   = 0x30,
    OBD_PIDS_DISTANCE_TRAVELED_SINCE_CODES_CLEARED = 0x31,
    OBD_PIDS_EVAPORATIVE_SYSTEM_VAPOR_PRESSURE = 0x32,
    OBD_PIDS_ABSOLUTE_BAROMETRIC_PRESSURE   = 0x33,
    OBD_PIDS_OXYGEN_SENSOR_1_AIR_FUEL_RATIO_CURRENT = 0x34,
    OBD_PIDS_OXYGEN_SENSOR_2_AIR_FUEL_RATIO_CURRENT = 0x35,
    OBD_PIDS_OXYGEN_SENSOR_3_AIR_FUEL_RATIO_CURRENT = 0x36,
    OBD_PIDS_OXYGEN_SENSOR_4_AIR_FUEL_RATIO_CURRENT = 0x37,
    OBD_PIDS_OXYGEN_SENSOR_5_AIR_FUEL_RATIO_CURRENT = 0x38,
    OBD_PIDS_OXYGEN_SENSOR_6_AIR_FUEL_RATIO_CURRENT = 0x39,
    OBD_PIDS_OXYGEN_SENSOR_7_AIR_FUEL_RATIO_CURRENT = 0x3A,
    OBD_PIDS_OXYGEN_SENSOR_8_AIR_FUEL_RATIO_CURRENT = 0x3B,
    OBD_PIDS_CATALYST_TEMPERATURE_BANK_1_SENSOR_1 = 0x3C,
    OBD_PIDS_CATALYST_TEMPERATURE_BANK_2_SENSOR_1 = 0x3D,
    OBD_PIDS_CATALYST_TEMPERATURE_BANK_1_SENSOR_2 = 0x3E,
    OBD_PIDS_CATALYST_TEMPERATURE_BANK_2_SENSOR_2 = 0x3F,
    OBD_PIDS_SUPPORTED_41_TO_60 = 0x40
};